version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Checking {{ ProviderName }}-{{ ProviderType }}"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Checking {{ ProviderName }}-{{ ProviderType }}"
  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Deploying {{ ProviderName }}-{{ ProviderType }}"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold